project_id = "lnchwlswprpegesupimg"

[functions.chat]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.smart-agent]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
